server:
  port: 8082
logging:
  level:
    cn.itsource.controller: debug
spring:
  application:
    name: STORE-ZUUL

#/plat/**的请求全交到STORE-PLAT服务中去
zuul:
 ignoredServices: '*' #不能使用服务名访问
 routes:
  plat:
    path: /plat/**
    serviceId: STORE-PLAT
  product:
    path: /product/**
    serviceId: STORE-PRODUCT
  common:
    path: /common/**
    serviceId: STORE-COMMON
#zuul超时时间的设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
zuul:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000