server:
  port: 7777
  max-http-header-size: 10000000 #服务器允许的请求头的最大长度

logging:
  level:
    cn.itsource.controller: debug

spring:
  application:
    name: STORE-COMMON
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
    repositories:
      enabled: true