server:
  port: 8082
logging:
  level:
    cn.itsource.controller: debug
spring:
  application:
    name: STORE-ZUUL
eureka:
  instance:
    prefer-ip-address: true #以ip注册到erueka中而不是主机名
  client:
    serviceUrl:
      defaultZone: http://ROOT:880811@localhost:8761/eureka/ #eureka的注册地址876

#/plat/**的请求全交到STORE-PLAT服务中去
zuul:
 ignoredServices: '*' #不能使用服务名访问
 routes:
  plat:
    path: /plat/**
    serviceId: STORE-PLAT

#  employee:
 #   path: /employee/**
  #  serviceId: SERVICE-zuul-EMPLOYEE

